mylist=[]
print("Blank list:")
print(mylist)
list=[1,2,3,4,5,6,7]
print("\nList of numbers: ")
print(list)
list1=["going","to","school"]
print("\nList containing multiple values: ")
print(list1)
list2=[["going","to"],["school"]]
print("\nMulti-Dimensional List: ")
print(list2)
list3=[1,2,3,4,5,2,3,4,6,]
print("\nList with the dupicate values: ")
print(list3)
list4=[1,2,4,5,"apple",7,8]
print("\nList with the use of mixed values: ")
print("Accessing a element from the list")
print(list[0])
print(list2[1])
print("Accessing a element from a Multi-Dimensional list")
print(list2[0][1])
print(list2[1][0])
print("Accessing element using negative indexing")
print(list[-1])
print(list4[-3])
print("length of the list:")
print(len(list2))

mylist.append(1)
mylist.append(5)
mylist.append(8)
print("\nlist after Addition of Three elements: ")
print(mylist)
for i in range(1, 5):
    mylist.append(i)
print("\nlist after Addition of elements from 1-5: ")
print(mylist)
mylist.append((5, 6))
print("\nlist after Addition of a Tuple: ")
print(mylist)
mylist.append(list1)
print("\nlist after Addition of a list: ")
print(mylist)
list5= [1,2,3,4]
print("initial list: ")
print(list5)
list5.insert(5,12)
list5.insert(8, "sasi")
print("\nlist after performing insert Operation: ")
print(list5)
list5.extend([8, "going", "kushi"])
print("\nList after performing Extend Operation: ")
print(list5)
mylist.reverse()
mylist.remove(5)
mylist.remove(3)
print("\nlist after Removal of two elements: ")
print(mylist)
list6=[1,2,3,4,5,6,7,8,9]
for i in range(1, 4):
    list6.remove(i)
print("\nlist after Removing a range of elements: ")
print(list6)
list6.pop()
print("\nlist after popping an element: ")
print(list6)
list6.pop(2)
print("\nlist after popping a specific element: ")
print(list6)
list7=[10,20,30,40,50,60,70,80]
print("\nlist index 0:5: ")
print(list7[0:5])
print(list7[4:])
print(list7[:])
print("\nlist negative index 0:5: ")
print(list7[-2:])
print(list7[::-5])