tuple1 = ()
print("Initial empty tuple: ")
print(tuple1)
tuple2=('going','school')
print("/n tuple using strings:tuple1")
print(tuple2)
list = [1, 2, 4, 5, 6]
print("\n tuple using List: ")
print(tuple(list))
tuple3 = tuple('elephant')
print("\ntuple with the use of function:tuple3 ")
print(tuple3)
tuple4 = (5, 'hello', 7, 'world')
print("\ntuple with mixed datatypes:tuple4 ")
print(tuple4)
tuple5= (10,20,30,40)
tuple6 = ('car', 'bike')
tuple7 = (tuple5, tuple6)
print("\ntuple with nested tuples:tuple7 ")
print(tuple7)
tuple8 = ('hello',) * 3
print("\ntuple with repetition:tuple8  ")
print(tuple8)
tuple9 = ('world')
n = 5
print("\ntuple with a loop")
for i in range(int(n)):
    tuple9 = (tuple9,)
    print(tuple9)
